# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'docker-swarm-pool'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/triplea-monorepo'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employee-triple-a/consumer/Dockerfile'
        tags: |
          $(tag)
