# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildD
  displayName: Dev Build image
  jobs:
  - job: Build
    displayName: Dev Build
    pool:
      name: 'prod-agent-pool'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/employee-triplea-monorepo'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employee-triple-a/consumer/Dockerfile'
        tags: |
          $(tag)



- stage: BuildU
  displayName: UAT Build image
  jobs:
  - job: Build
    displayName: UAT Build
    pool:
      name: 'prod-agent-pool'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/employee-triplea-monorepo'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employee-triple-a/consumer/Dockerfile'
        tags: |
          $(tag)




