# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/employee-triplea-monorepo'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employee-triple-a/consumer/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/employer-triplea-monorepo'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employer-triple-a/consumer/Dockerfile'
        tags: |
          $(tag)


    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/user-operation-triplea-monorepo'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/user-operation-triple-a/consumer/Dockerfile'
        tags: |
          $(tag)




    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/employee-triplea-monorepo-producer'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employee-triple-a/producer/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build a image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/employer-triplea-monorepo-producer'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/employer-triple-a/producer/Dockerfile'
        tags: |
          $(tag)


    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'orbis-docker-con'
        repository: 'orbispay/user-operation-triplea-monorepo-producer'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/packages/user-operation-triple-a/producer/Dockerfile'
        tags: |
          $(tag)
