version: '3.5'

services:
    #######################################
    # Triple A
    #######################################
    triple-a-user-ops-operations:
        container_name: triple-a-user-ops-operations
        env_file: "env/${ENV}.env"
        build:
            context: "."
            dockerfile: Dockerfile
        image: triple-a-user-ops-operations

        networks:
            - orbis-net
        ports:
            - "4105:4000"
        command: npm run start:prod
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
        orbis-net:
            name: orbis-network
            ipam:
                driver: default
                config:
                    - subnet: "172.16.238.0/24"
                    - subnet: "2001:3984:3989::/64"
