export enum Operations {
  LOGIN = 'LOGIN',
  UPDATE = 'UPDATE',
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  BLOCK = 'BLOCK',
  UNBLOCK = 'UNBLOCK',
  REJECTED = 'REJECTED',
  UPDATE_USERTYPE_NAME = 'UPDATE_ROLE_NAME',
	UPDATE_USERTYPE_PERMISSIONS = 'UPDATE_ROLE_PERMISSIONS',
}
