version: '3.5'

services:
    #######################################
    # Triple-A
    #######################################
     triple-a-employee-db-writer:
        container_name: triple-a-employee-db-writer
        env_file: "env/${ENV}.env"
        build:
            context: "."
            dockerfile: Dockerfile
        image: triple-a-employee-db-writer

        networks:
            - orbis-net
        ports:
            - "4100:4000"
        command: npm run start:prod
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
        orbis-net:
            name: orbis-network
            ipam:
                driver: default
                config:
                    - subnet: "172.16.238.0/24"
                    - subnet: "2001:3984:3989::/64"
