export enum Operations {
	UPDATE = 'UPDATE',
	CREATE = 'CREATE',
	DELETE = 'DELETE',
	ENABLE = 'ENABLE',
	DISABLE = 'DISABLE',
	RESET_PASSWORD = 'RESET_PASSWORD',
	UPDATE_USERTYPE_NAME = 'UPDATE_ROLE_NAME',
	UPDATE_USERTYPE_PERMISSIONS = 'UPDATE_ROLE_PERMISSIONS',
}
